version: "3.8"

services:
  mycloud_microservice:
    container_name: mycloud_microservice
    build:
      context: ./
      dockerfile: docker/Dockerfile.HotReload
    ports:
      - "5001:5001"
      # - "5555:5555"
      # - "7070:7070"
    environment:
      - PORT=5001
    depends_on:
      - postgresql
      - redis
    restart: always
    volumes:
      - ./:/app
    networks:
      - mycloud_network

  redis:
    image: redis:6.0.9-alpine
    container_name: mycloud_redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - mycloud_network

  postgresql:
    image: postgres:16
    container_name: mycloud_postgresql
    ports:
      - "5431:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mycloud_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mycloud_network


volumes:  
  pgdata: {}

networks:
  mycloud_network:
    driver: bridge