FROM golang:1.21

#ENV TZ=Europe/Moscow
#RUN ln -snf /usr/shar/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENV config=docker

WORKDIR /app

COPY ./ /app

RUN go mod download

RUN go get github.com/githubnemo/CompileDaemon

EXPOSE 5001

ENTRYPOINT CompileDaemon --build="go build server/cmd/mycloud/main.go" --command=./main
